### ISSUE TITLE
Icons dos not render

### ISSUE THREAD

**Issue by FalcoSuessgott** [daniruiz/dotfiles#2]
Hi,

some of the icons does not render.
```
 user    …/git/Awesome-CV     master ± ●  
╰ k                                                                                06:30    12.97G  
```

I installed the Hack Nerd Font:
```
fc-list| grep Hack                                                               06:31    12.97G  
../share/fonts/Hack Bold Nerd Font Complete.ttf: Hack Nerd Font:style=Bold
```

Any Ideas?

**Comment by daniruiz** [comment]
Wich terminal are you using? you need to manually select Nerd Font as the terminal font (if you are using gnome-terminal you'll need to change the monospace font from gnome-tweaks)

**Comment by FalcoSuessgott** [comment]
Using tilix.
But thanks your advice worked. Choosing Hack Bold Font in gnome-tweaks and tilix worked for me. 
Thanks !:)
