### ISSUE TITLE
Can't see all icons

### ISSUE THREAD

**Issue by fabifont** [daniruiz/dotfiles#3]
Hi, I followed your guide and I installed some packages like nerd-fonts-complete and icons-in-terminal, but I can't see all the icons like the "home" icon or the "clock" icon. How can I fix that?
This is the screenshot: https://ibb.co/KF3JCFx
The .zshrc I used is like your with different colors

**Comment by daniruiz** [comment]
Which terminal are you using?

**Comment by fabifont** [comment]
I am using termite but on my other computer it works fine as you can see here: https://ibb.co/3dFP8kC
So what am I missing ?

**Comment by daniruiz** [comment]
Then this is an issue of the terminal. Maybe they can help you better than me, as this repo is only the configuration that I use, there is no program, only settings
