### ISSUE TITLE
hello, theme install help~~~

### ISSUE THREAD

**Issue by HaloXie** [daniruiz/dotfiles#5]
Hello, this is indeed a very cool theme, the configuration and steps are indeed very detailed.
Can you provide a general command to achieve the same effect, because the document is too detailed, I tried it and did not achieve the desired effect

1. On-my-zsh has been installed
2. The powerlevel10k theme has been downloaded
3. Download the zip package from https://github.com/daniruiz/dotfiles and execute install.sh
4. The corresponding screenshots as following
![image](https://user-images.githubusercontent.com/22462009/104847396-b378eb00-591a-11eb-9c13-8e292ca38a47.png)

![image](https://user-images.githubusercontent.com/22462009/104847409-cab7d880-591a-11eb-854d-d7295b17f7cb.png)

**Comment by KushagraKarira** [comment]
The files are daniruiz own configuration and not expected to work on every system.
like the .desktop files or tilix configuration imported.

Though you can try running `p10k configure` to configure powerlevel10k theme you installed, the configuration cannot look exactly like [this](https://raw.githubusercontent.com/daniruiz/dotfiles/master/Screenshots/terminal.png) but try and find what suits you best.

**Comment by daniruiz** [comment]
Yes, sorry... this are my personal files.
In fact, if you are using a mac none of the things that the install.sh script does matter. Just read the blog a tweak it how you like it :wink:
