### ISSUE TITLE
How to uninstall 

### ISSUE THREAD

**Issue by Ran-Xing** [daniruiz/dotfiles#7]
```
$ ls                                                                     130 x
ls: illegal option -- -
usage: ls [-@ABCFGHLOPRSTUWabcdefghiklmnopqrstuwx1%] [file ...]
```

**Comment by KushagraKarira** [comment]
It looks like a problem with shell alias
`rm ~/.bashrc `or `rm ~/.zshrc` whichever is applicable,
better solution would be to edit these file and comment out unneeded tweaks
