### ISSUE TITLE
Pimp my terminal typo

### ISSUE THREAD

**Issue by ghost** [daniruiz/dotfiles#8]
There is a typo on the alias "tree=lsd".

It's written there: "command -v lsd > /dev/null && alias ls='lsd --tree'".
That way, it will overwrite the ls alias that we want, so it should be: command -v lsd > /dev/null && alias tree='lsd --tree'

Same thing happens to "cat=bat" and "less=bat".

**Comment by daniruiz** [comment]
Just fixed it ;)
Sorry for the long delay, I've been really busy
